# Generated by Django 5.2.1 on 2025-05-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartBiz_Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticles', models.PositiveIntegerField()),
                ('prixTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('articles', models.ManyToManyField(related_name='ventes', to='SmartBiz_Manager.article')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFacture', models.CharField(max_length=50, unique=True)),
                ('nomClient', models.CharField(max_length=100)),
                ('telephoneClient', models.CharField(max_length=20)),
                ('dateEmission', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modePaiement', models.CharField(max_length=50)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='SmartBiz_Manager.vente')),
            ],
        ),
    ]
